### ISSUE TITLE
[Question] Cannot create folder

### ISSUE THREAD

**Issue by khannzxc** [khusika/FeelIt#41]
How to create  new posts

```hugo new posts/istpost```

The above command create a file ```istpost.md``` in ```content/posts``` folder.
But the default posts are in this format ```posts/Folder/folder.md```

My question is will we create folder manually?

**Comment by khannzxc** [comment]
Actually i am integrating Netlify CMS. I have integrated it to other hugo themes in the past.
But in this theme the post are saved in a folder like ```posts/POSTNAME/POSTNAME.md```

How can I tell netlify to create a folder with same name as post title?

my netlify.toml is

```
backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: static/images/uploads
public_folder: /images/uploads

collections:
  - name: "post"
    label: "Post"
    folder: "exampleSite/content/posts"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      #- { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "string" }
      # - { label: 'Side Image', name: 'image', widget: 'image' }
      - { label: "Body", name: "body", widget: "markdown" }
      # - { label: 'Libraries', name: 'libraries', widget: 'list' }
      #- { label: "Categories", name: "categories", widget: "list" }
      #- { label: "Tags", name: "tags", widget: "list" }
      #- { label: "Series", name: "series", widget: "list" }

```
