### ISSUE TITLE
[QUESTION] Image not showing

### ISSUE THREAD

**Issue by khannzxc** [khusika/FeelIt#43]
I have create a post in ```posts``` folder. And in front matter I have added the image name and src
```
resources:
  - name: "featured-image"
    src: "featured-image.webp"
```
But the image is not displaying. Clear the cache several times but not working.
But in the default posts images are displaying correctly.

Steps to follow

- simply create a post in ```posts``` folder
- copy the images in ```posts``` folder
- add the below code in front matter
- ```resources:
  - name: "featured-image"
    src: "featured-image.webp"
But still not showing images even after clearing cache

**Comment by khusika** [comment]
May i know your specific post & image location?

**Comment by khannzxc** [comment]
My post location is ```exampleSite/content/posts/test/test.md```
and my image location is ```exampleSite/content/posts/test/```

and the front matter is

```
---
weight: 1
title: "Test Post"
date: 2020-03-06T21:29:01+08:00
lastmod: 2020-03-05T21:29:01+08:00
draft: false
author: "FeelIt"
authorLink: "https://feelit.khusika.com"
description: "Discover what the Hugo - FeelIt theme is all about and the core-concepts behind it."
# featuredImage: "featured-image"
# featuredImagePreview: "featured-image-preview.webp"
resources:
  - name: "featured-image"
    src: "featured-image.webp"
tags: ["installation", "configuration"]
categories: ["documentation"]

lightgallery: false

toc:
  auto: false
---

Some body text

```

and the error pics are:
[
![dellll](https://user-images.githubusercontent.com/40522970/126491055-c1a00a2e-ea5d-4507-a054-949f2b30200f.JPG)
](url)
