### ISSUE TITLE
[FEATURE] Can't use Font Awesome in the [params.home.profile].subtitle

### ISSUE THREAD

**Issue by chengleqi** [khusika/FeelIt#56]
I enable the fontawesome, It can be used in the [params.home.profile].title, but it can't be used in the [params.home.profile].subtitle.
```toml
title = "<i class='fas fa-dharmachakra'></i>" #it can be shown correctly
subtitle = "<i class='fas fa-dharmachakra'></i>" # nothing
```
I also tried the shortcode , It just show a string `:(fas fa-dharmachakra):`
It's wired, I don't know why.
and fontawesome alse can't be used in the [params.header.title].logo and [params.header.title].name
