### ISSUE TITLE
[BUG] featured-image is not rendered

### ISSUE THREAD

**Issue by antedoro** [khusika/FeelIt#67]
### Describe the bug

When I start `hugo server -D ` 
_featured-image-preview.webp_ on homepage and _featuredimage.webp_ it's not rendered. 
(Sorry it's probably not a bug but I need some support to solve it)

### Expected behavior

Frontmatter's post it's correctly configured as: 
```
resources:
- name: "featured-image"
  src: "featured-image.webp"
- name: "featured-image-preview"
  src: "featured-image-preview.webp"
```
but featured image its not displayed

### Build Environment

- OS: [macOS]
- Theme version/commit: [1.0.X, [0548952](https://github.com/khusika/FeelIt/commits/0548952d216928c072948a91beb6279842bbf783)]
- Hugo version: [0.88.0+extended]

### Preview Environment

- OS: [macOS]
- Browser [Chrome, Edge, Firefox]
