### ISSUE TITLE
[BUG] Syntax highlighting theme not working

### ISSUE THREAD

**Issue by Pascal3366** [khusika/FeelIt#93]
### Describe the bug

I tried to change the syntax highlighting theme to Dracula like so:

```toml
[markup.highlight]
    anchorLineNos = false
    codeFences = false  # Disable Hugo's code highlighter as it conflicts with Academic's highligher.
    guessSyntax = true
    hl_Lines = ''
    lineAnchors = ''
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    # false is a necessary configuration
    # (https://github.com/khusika/FeelIt/issues/158)
    noClasses = true
    noHl = false
    tabWidth = 4
    pygmentsCodefences = true
    pygmentsStyle = "dracula"
```

However I am not able to change the default code highlighter scheme of this theme

### Expected behavior

The syntax highlighting theme should get changed.

### Build Environment

- OS: Fedora
- Theme version/commit: 1.0.1 (https://github.com/khusika/FeelIt/commits/0548952d216928c072948a91beb6279842bbf783)]
- Hugo version: 0.95.0+extended

### Preview Environment

- OS: Fedora
- Browser Chrome
